default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']

    # Ensure we have the latest certificates and profiles
    # match(type: "appstore", readonly: is_ci) 

    # Build the application
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")

    # Upload to TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
